"""Como cada tweak aparece para quem joga.

O catálogo técnico (fonte, custo, métrica) continua nos módulos. Aqui mora só a
tradução para a tela: em qual objetivo o item entra (Mais FPS, Menos delay...),
as etiquetas curtas, o tamanho do impacto e uma explicação que qualquer
cliente entende sem saber o que é MMCSS.

Regra: nenhum texto aqui promete número. "Mais FPS" quer dizer "mexe no que
limita o FPS", e o impacto é relativo aos outros itens da lista.
"""
from __future__ import annotations

from typing import Any, Dict, List

GOALS: List[Dict[str, str]] = [
    {"id": "fps", "label": "Mais FPS", "icon": "fps",
     "hint": "Tira do caminho o que segura o desempenho da placa de vídeo e do processador."},
    {"id": "delay", "label": "Menos delay", "icon": "delay",
     "hint": "Clique, tecla e movimento chegam mais rápido na tela (menos input lag)."},
    {"id": "stutter", "label": "Sem travadinhas", "icon": "stutter",
     "hint": "Frametime estável: menos engasgos, quedas de 1% low e congeladas no meio da partida."},
    {"id": "ping", "label": "Internet e ping", "icon": "ping",
     "hint": "Conexão mais estável no jogo: menos picos de ping e menos quedas."},
    {"id": "leve", "label": "Windows leve", "icon": "leve",
     "hint": "Menos processos, serviços e tarefas rodando escondidos gastando CPU, RAM e disco."},
    {"id": "privacidade", "label": "Privacidade", "icon": "privacy",
     "hint": "Menos dados enviados para a Microsoft e menos propaganda."},
    {"id": "visual", "label": "Visual e conforto", "icon": "visual",
     "hint": "Preferências de aparência e de uso do Windows. Não mudam o FPS."},
    {"id": "reparo", "label": "Consertos", "icon": "repair",
     "hint": "Desfaz estragos de outros otimizadores. Num PC saudável não há nada a fazer aqui."},
    {"id": "avancado", "label": "Avançado", "icon": "lab",
     "hint": "Itens com custo real ou resultado que varia por PC. Aplique, teste e desfaça se não gostar."},
]

GOAL_IDS = {g["id"] for g in GOALS}

# id: (objetivo, etiquetas, impacto 1-3, título curto, o que faz em uma frase simples)
_T = {
    # ---------------- Mais FPS ----------------
    "power_plan": ("fps", ["+FPS", "-STUTTER"], 3, "Plano de energia AZOR",
                   "Deixa o processador subir para o clock máximo na hora que o jogo pede."),
    "power_throttling_off": ("fps", ["+FPS"], 2, "Sem economia forçada de CPU",
                             "Impede o Windows de colocar o jogo e o Discord em modo econômico."),
    "game_mode": ("fps", ["+FPS", "-STUTTER"], 2, "Modo de Jogo do Windows",
                  "Faz o Windows dar prioridade ao jogo e segurar atualizações durante a partida."),
    "game_dvr": ("fps", ["+FPS"], 2, "Sem gravação escondida da Xbox Game Bar",
                 "Para a Game Bar de gravar a partida o tempo todo em segundo plano."),
    "gamedvr_machine_policy": ("fps", ["+FPS"], 1, "Bloqueio da gravação para todos os usuários",
                               "Garante que a gravação escondida não volte sozinha, nem em outro usuário."),
    "hags": ("fps", ["+FPS", "-DELAY"], 2, "Agendamento de GPU por hardware",
             "A própria placa de vídeo organiza a fila de quadros, aliviando o processador."),
    "display_max_refresh": ("fps", ["+FPS", "-DELAY"], 3, "Monitor na taxa máxima (Hz)",
                            "Monitor de 144 Hz em 60 Hz só mostra 60 FPS. Coloca na taxa máxima que ele aceita."),
    "all_games_gpu": ("fps", ["+FPS"], 3, "Jogos na placa de vídeo dedicada",
                      "Em notebook e PC com vídeo integrado, força os jogos a usar a placa mais forte."),
    "fortnite_gpu": ("fps", ["+FPS"], 2, "Fortnite na placa de vídeo dedicada",
                     "Garante que o Fortnite rode na placa de vídeo mais forte do PC."),
    "memory_integrity_off": ("avancado", ["+FPS", "SEGURANÇA-"], 3, "Desligar a Integridade de Memória (VBS)",
                             "Tira uma camada de virtualização que pesa no processador. Alguns anti-cheats exigem ela ligada."),
    "game_priority_engine": ("fps", ["+FPS", "-STUTTER"], 2, "Prioridade alta automática para o jogo",
                             "Enquanto o AZOR estiver aberto, o jogo sobe para prioridade Alta sozinho."),
    "visual_effects": ("fps", ["+LEVE", "-DELAY"], 1, "Efeitos visuais no modo desempenho",
                       "Desliga animações e sombras do Windows. A área de trabalho responde na hora."),
    "transparency": ("fps", ["+LEVE"], 1, "Sem transparência no Windows",
                     "Tira o efeito de vidro da barra e do menu. Alivia a placa de vídeo fora do jogo."),
    "vrr_windowed": ("delay", ["-DELAY", "+FPS"], 2, "Jogos em janela otimizados (VRR)",
                     "Jogo em janela sem borda passa a ter o mesmo caminho rápido da tela cheia."),
    "defender_game_exclusions": ("stutter", ["-STUTTER", "LOADING"], 2, "Antivírus fora das pastas de jogo",
                                 "O Defender para de verificar cada arquivo que o jogo carrega. Carregamento e shader mais rápidos."),
    "kernel_no_paging": ("stutter", ["-STUTTER"], 1, "Núcleo do Windows sempre na RAM",
                         "Impede o Windows de mandar partes dele para o disco no meio do jogo (só com 16 GB+)."),
    "memory_compression_off": ("avancado", ["-STUTTER"], 1, "Sem compressão de memória (32 GB+)",
                               "Com muita RAM, a compressão vira trabalho extra para o processador."),
    "automatic_pagefile": ("reparo", ["-STUTTER", "REPARO"], 2, "Memória virtual automática",
                           "Religa o arquivo de paginação se alguém desligou. Sem ele, jogos fecham do nada."),

    # ---------------- Menos delay ----------------
    "latency_timer": ("delay", ["-DELAY"], 2, "Timer do Windows em 0,5 ms",
                      "O relógio interno do Windows passa a acordar mais vezes: comandos processados mais rápido."),
    "global_timer_resolution": ("delay", ["-DELAY"], 2, "Timer rápido para o PC inteiro",
                                "Faz o timer de 0,5 ms valer para o jogo, não só para o AZOR. Exige reiniciar."),
    "mouse_acceleration_off": ("delay", ["MIRA", "-DELAY"], 3, "Mouse sem aceleração",
                               "A mesma distância do mouse vira sempre a mesma distância na tela. Base da mira."),
    "usb_suspend_off": ("delay", ["-DELAY"], 2, "USB sempre acordado",
                        "Mouse, teclado e headset não 'dormem' e não demoram para responder depois de parados."),
    "usb_hub_power_off": ("delay", ["-DELAY"], 2, "Portas USB sem economia de energia",
                          "O Windows para de desligar as portas USB da placa-mãe para economizar."),
    "fullscreen_exclusive": ("delay", ["-DELAY", "+FPS"], 2, "Tela cheia exclusiva de verdade",
                             "Tira o Windows do meio do caminho entre o quadro pronto e o monitor. Overlays podem sumir."),
    "fortnite_fullscreen_exclusive": ("delay", ["-DELAY"], 2, "Tela cheia exclusiva só no Fortnite",
                                      "Mesmo ganho de delay, só dentro do Fortnite. O resto do PC não muda."),
    "gpu_interrupt_priority": ("delay", ["-DELAY"], 1, "Placa de vídeo atendida primeiro",
                               "Quando dois aparelhos chamam o processador ao mesmo tempo, a placa de vídeo passa na frente."),
    "keyboard_repeat_fast": ("visual", ["TECLADO"], 1, "Repetição de tecla no máximo",
                             "Segurar uma tecla repete mais rápido. Não muda o delay dentro do jogo."),
    "menu_show_delay": ("visual", ["-DELAY"], 1, "Menus do Windows instantâneos",
                        "Menus abrem na hora em vez de esperar 400 ms."),
    "usb_interrupts_ecores": ("avancado", ["-DELAY", "CONTROLE"], 1, "USB do controle nos núcleos E",
                              "Para controle ou mouse de 4K/8K Hz em CPU Intel 12ª geração+: tira as interrupções do núcleo do jogo."),
    "sticky_keys_off": ("delay", ["SEM POP-UP"], 2, "Sem pop-up das Teclas de Aderência",
                        "Apertar Shift 5 vezes no jogo não abre mais aquela janela que tira o foco."),
    "end_task_taskbar": ("visual", ["CONFORTO"], 1, "Fechar jogo travado pela barra de tarefas",
                         "Botão direito no jogo travado > Finalizar tarefa. Sem abrir o Gerenciador."),
    "game_bar_panel_off": ("delay", ["SEM POP-UP"], 1, "Game Bar não abre ao iniciar o jogo",
                           "O painel da Game Bar não rouba mais o foco no primeiro segundo da partida."),

    # ---------------- Sem travadinhas ----------------
    "nvme_idle_never": ("stutter", ["-STUTTER", "LOADING"], 1, "SSD NVMe sempre pronto",
                        "O SSD não entra em economia, então textura carregada no meio do jogo não engasga."),
    "azor_memory_engine": ("stutter", ["-STUTTER", "RAM"], 2, "Motor de memória AZOR",
                           "Libera a memória em espera só quando ela está acabando (o que o ISLC faz), sem jogar cache fora à toa."),
    "system_responsiveness": ("stutter", ["+FPS", "-STUTTER"], 2, "Mais processador para o jogo",
                              "O Windows reserva menos CPU para tarefas de fundo enquanto você joga."),
    "network_throttling_off": ("ping", ["PING", "-STUTTER"], 2, "Sem limite de pacotes de rede",
                               "Tira um freio que o Windows põe na rede enquanto toca som ou vídeo."),
    "fast_startup_off": ("stutter", ["ESTÁVEL"], 1, "Desligar de verdade (sem Inicialização Rápida)",
                         "Faz o 'reiniciar' e o 'desligar' limparem o Windows de verdade. Ajustes e drivers pegam."),
    "hibernate_off": ("leve", ["+ESPAÇO"], 1, "Desligar a hibernação",
                      "Libera vários GB no disco (arquivo hiberfil.sys). Só em desktop."),
    "startup_delay_off": ("leve", ["BOOT"], 1, "Programas do boot sem espera",
                          "O Windows para de esperar 10 segundos antes de abrir os programas de inicialização."),
    "ntfs_last_access_off": ("stutter", ["-STUTTER", "DISCO"], 1, "Disco sem anotar cada leitura",
                             "Cada arquivo que o jogo lê deixa de gerar uma escrita extra no disco."),
    "ntfs_short_names_off": ("leve", ["DISCO"], 1, "Sem nomes curtos antigos (8.3)",
                             "O disco para de criar um segundo nome estilo DOS para cada arquivo novo."),

    # ---------------- Internet e ping ----------------
    "nagle_off": ("ping", ["PING", "-DELAY"], 1, "Rede sem agrupar pacotes (Nagle)",
                  "A placa de rede para de segurar pacotes pequenos esperando juntar. Ajuda jogos que usam TCP."),
    "nic_interrupt_moderation_off": ("ping", ["PING", "-DELAY"], 2, "Placa de rede sem espera",
                                     "Cada pacote chega ao sistema na hora, em vez de esperar um grupo. Usa um pouco mais de CPU."),
    "nic_power_saving_off": ("ping", ["PING", "SEM QUEDA"], 2, "Placa de rede sem economia de energia",
                             "O Windows não desliga mais a placa de rede para economizar: acabam as quedas de alguns segundos."),
    "nic_green_ethernet_off": ("ping", ["PING"], 2, "Cabo de rede sem modo econômico",
                               "Desliga o 'Ethernet verde', que causa picos isolados de ping."),
    "nic_rss_on": ("ping", ["PING", "+FPS"], 1, "Rede dividida entre os núcleos",
                   "O trabalho da placa de rede se espalha pelos núcleos e para de disputar com o jogo."),
    "delivery_optimization_off": ("ping", ["PING", "UPLOAD"], 2, "Windows sem usar sua internet para outros PCs",
                                  "O Windows para de enviar atualizações para computadores de estranhos pela sua conexão."),
    "ipv4_preferred": ("ping", ["INTERNET"], 1, "Preferir IPv4",
                       "Resolve internet instável quando o IPv6 do provedor está mal configurado."),

    # ---------------- Windows leve ----------------
    "services_lite": ("leve", ["+LEVE", "RAM"], 2, "Tirar serviços inúteis do boot",
                      "Mapas, atualizadores do Edge/Google/Adobe, arquivos offline e outros saem do boot."),
    "services_extreme": ("leve", ["+LEVE", "DISCO"], 1, "Desligar indexador de pesquisa",
                         "O indexador para de ler o disco inteiro de tempos em tempos. A busca fica mais lenta."),
    "telemetry_tasks_off": ("leve", ["+LEVE", "-STUTTER"], 3, "Desligar tarefas de telemetria",
                            "Acaba com o 'disco em 100% do nada' do CompatTelRunner e das tarefas de relatório."),
    "diagtrack_off": ("leve", ["+LEVE"], 2, "Desligar o serviço de telemetria",
                      "O serviço que coleta e envia dados de uso para a Microsoft para de rodar."),
    "background_apps": ("leve", ["+LEVE", "RAM"], 2, "Apps da loja sem rodar escondidos",
                        "Apps como Fotos, Clima e Mensagens param de funcionar em segundo plano."),
    "edge_background_off": ("leve", ["+LEVE", "RAM"], 2, "Edge sem rodar escondido",
                            "O Edge para de abrir sozinho no boot e de ficar na memória depois de fechado."),
    "copilot_recall_off": ("leve", ["+LEVE", "RAM"], 2, "Desligar Copilot e Recall",
                           "O Recall para de tirar print da tela o tempo todo e o Copilot sai da memória."),
    "audio_ducking_off": ("delay", ["SOM", "CALL"], 2, "Som do jogo não abaixa em call",
                          "O Windows para de abaixar em 80% o som do jogo quando você entra no Discord."),
    "update_no_reboot": ("stutter", ["ESTÁVEL"], 2, "Windows Update sem reiniciar sozinho",
                         "Acabou o 'reiniciando em 15 minutos' no meio da partida."),
    "wu_drivers_off": ("fps", ["+FPS", "DRIVER"], 2, "Windows Update não troca o driver de vídeo",
                       "Impede o Windows de instalar por cima um driver de vídeo mais velho que o seu."),
    "explorer_ads_off": ("leve", ["SEM LIXO"], 1, "Explorador sem propaganda",
                         "Some a propaganda do OneDrive e do Microsoft 365 no Explorador e no Iniciar."),
    "remote_assistance_off": ("leve", ["+LEVE", "SEGURANÇA"], 1, "Assistência Remota desligada",
                              "Uma porta a menos aberta. AnyDesk e TeamViewer continuam funcionando."),
    "shared_experiences_off": ("leve", ["+LEVE"], 1, "Sem procurar aparelhos por perto",
                               "O Windows para de varrer Bluetooth e Wi-Fi atrás de celular para 'continuar no PC'."),
    "services_more": ("leve", ["+LEVE", "RAM"], 2, "Tirar do boot diagnóstico, telefonia e NFC",
                      "Mais serviços que um PC de jogo não usa saem da memória."),
    "wer_off": ("leve", ["+LEVE", "DISCO"], 1, "Sem relatório de erros do Windows",
                "Depois de um crash o Windows não fica juntando e enviando relatório em segundo plano."),
    "spotlight_off": ("leve", ["+LEVE", "SEM LIXO"], 1, "Sem Spotlight na tela de bloqueio",
                      "O Windows para de baixar imagens e propaganda para a tela de bloqueio."),
    "tips_setup_off": ("leve", ["+LEVE", "POP-UP"], 1, "Sem 'Termine de configurar seu PC'",
                       "Some a tela cheia que aparece depois das atualizações empurrando OneDrive e Microsoft 365."),
    "consumer_features_off": ("leve", ["+LEVE", "SEM LIXO"], 2, "Bloquear apps que o Windows instala sozinho",
                              "Candy Crush, TikTok e outros apps de propaganda param de aparecer sozinhos."),
    "widgets": ("leve", ["+LEVE"], 1, "Esconder Widgets",
                "Tira o painel de notícias e clima da barra, que ficava carregando conteúdo."),
    "search_highlights_off": ("leve", ["+LEVE"], 1, "Pesquisa sem destaques da internet",
                              "A caixa de pesquisa para de buscar desenhos e notícias na internet."),
    "bing_search_off": ("leve", ["+LEVE"], 2, "Menu Iniciar sem Bing",
                        "Pesquisar no menu Iniciar fica só no PC: mais rápido e sem internet."),
    "device_metadata_off": ("leve", ["SEM LIXO"], 1, "Sem apps de fabricante automáticos",
                            "Conectar um aparelho novo não baixa mais programas de propaganda."),
    "windows_suggestions": ("leve", ["SEM LIXO"], 1, "Sem sugestões e propagandas do Windows",
                            "Tira anúncios e 'dicas' do menu Iniciar e das Configurações."),
    "spooler_off": ("leve", ["+LEVE"], 1, "Desligar o serviço de impressão",
                    "Só aparece se o PC não tem nenhuma impressora. Um processo a menos."),
    "telemetry_policy_min": ("privacidade", ["PRIVACIDADE"], 1, "Telemetria no mínimo",
                             "Diz ao Windows para coletar o mínimo de dados de diagnóstico."),
    "telemetry_full_off": ("privacidade", ["PRIVACIDADE"], 1, "Sem ID de anúncios e rastreio",
                           "Desliga o ID de propaganda, o envio de digitação e voz e os pedidos de avaliação."),
    "activity_history_off": ("privacidade", ["PRIVACIDADE", "+LEVE"], 1, "Sem histórico de atividades",
                             "O Windows para de anotar cada programa e arquivo que você abre."),
    "location_off": ("privacidade", ["PRIVACIDADE"], 1, "Desligar localização",
                     "Nenhum app sabe onde o PC está."),
    "sysmain_ssd_off": ("avancado", ["TESTE"], 1, "Testar sem o SysMain (só SSD)",
                        "Desliga o pré-carregamento de programas. Programas podem abrir mais devagar."),
    "prefetcher_ssd_off": ("avancado", ["TESTE"], 1, "Testar sem o Prefetcher (só SSD)",
                           "Desliga a leitura antecipada de programas. Programas podem abrir mais devagar."),
    "svchost_split_threshold": ("avancado", ["TESTE", "RAM"], 1, "Agrupar serviços em menos processos",
                                "Menos linhas no Gerenciador de Tarefas. Não dá FPS e reduz a estabilidade."),
    "win32_priority_separation": ("avancado", ["TESTE"], 1, "Quantum do agendador (Win32PrioritySeparation)",
                                  "Muda como o Windows divide o tempo de CPU. Em alguns PCs piora o jogo: teste."),
    "mmcss_games_priority": ("avancado", ["TESTE"], 1, "Perfil MMCSS de jogos em prioridade alta",
                             "Muito divulgado, pouco efeito: a maioria dos campos nem é usada pelo Windows."),
    "processor_idle_disable": ("avancado", ["TESTE", "CALOR"], 1, "CPU sem repouso",
                               "Todos os núcleos ficam acordados. Medido: derruba o turbo do núcleo que roda o jogo."),
    "tdr_delay": ("avancado", ["ESTÁVEL"], 1, "Mais tempo antes de reiniciar o driver de vídeo",
                  "Para quem vê 'o driver de vídeo parou de responder' em overclock. Não dá FPS."),
    "mpo_off": ("avancado", ["TESTE"], 1, "Desligar o MPO",
                "Só para quem tem tela piscando ou cintilando. Em alguns jogos trava a imagem."),
    "gpu_msi": ("avancado", ["RISCO"], 1, "MSI na placa de vídeo",
                "Drivers atuais já fazem isso sozinhos. Em PC antigo pode deixar sem imagem."),
    "usb_controller_msi": ("avancado", ["RISCO"], 1, "MSI no controlador USB",
                           "Pode deixar o PC sem mouse e teclado no próximo boot."),
    "storage_msi": ("avancado", ["RISCO"], 1, "MSI na controladora do SSD",
                    "Pode impedir o PC de ligar no próximo boot."),
    "reserved_storage_off": ("avancado", ["+ESPAÇO"], 1, "Liberar espaço reservado do Windows",
                             "Devolve de 7 a 10 GB que o Windows guarda para atualizações."),
    "bitlocker_off": ("avancado", ["DISCO", "SEGURANÇA-"], 1, "Desligar a criptografia do disco",
                      "O SSD para de criptografar cada leitura e escrita. Arquivos ficam desprotegidos se o PC for roubado."),

    # ---------------- Visual e conforto ----------------
    "dark_mode": ("visual", ["VISUAL"], 1, "Tema escuro", "Windows e apps no modo escuro."),
    "show_extensions": ("visual", ["SEGURANÇA+"], 1, "Mostrar extensões", "Mostra .exe, .zip, .png no nome dos arquivos."),
    "show_hidden_files": ("visual", ["VISUAL"], 1, "Mostrar arquivos ocultos", "Aparecem pastas como AppData."),
    "numlock_on": ("visual", ["TECLADO"], 1, "Num Lock ligado", "O teclado numérico já começa ligado."),
    "taskbar_search_hidden": ("visual", ["VISUAL"], 1, "Barra sem caixa de pesquisa", "Mais espaço na barra de tarefas."),
    "taskview_hidden": ("visual", ["VISUAL"], 1, "Barra sem Visão de Tarefas", "Tira o botão de áreas de trabalho."),
    "taskbar_left": ("visual", ["VISUAL"], 1, "Barra de tarefas à esquerda", "Botão Iniciar no canto, como no Windows 10."),
    "start_recommendations_off": ("visual", ["VISUAL"], 1, "Menu Iniciar limpo", "Sem recomendações e arquivos recentes."),
    "detailed_bsod": ("visual", ["DIAGNÓSTICO"], 1, "Tela azul detalhada", "Mostra o código do erro se o PC der tela azul."),
    "snap_off": ("visual", ["VISUAL"], 1, "Sem encaixe de janelas", "Janelas não grudam nas bordas."),
    "lockscreen_off": ("visual", ["BOOT"], 1, "Pular tela de bloqueio", "Vai direto para a senha."),
    "login_blur_off": ("visual", ["VISUAL"], 1, "Login sem desfoque", "Papel de parede nítido na senha."),
    "home_gallery_off": ("visual", ["VISUAL"], 1, "Explorador direto em Este Computador", "Sem Início e Galeria na lateral."),
    "notifications_off": ("visual", ["SEM POP-UP"], 1, "Sem notificações", "Nenhum aviso aparece na tela."),
    "storage_sense_off": ("visual", ["ARQUIVOS"], 1, "Sem limpeza automática do Windows", "O Windows não apaga arquivos sozinho."),
    "explorer_generic_folders": ("visual", ["+LEVE"], 1, "Explorador mais rápido", "Pastas grandes abrem sem esperar."),
    "classic_context_menu": ("visual", ["VISUAL"], 1, "Menu do botão direito completo", "Sem 'Mostrar mais opções'."),

    # ---------------- Consertos ----------------
    "system_restore_repair": ("reparo", ["REPARO"], 2, "Religar pontos de restauração",
                              "Volta a rede de segurança do Windows se alguém desligou."),
    "firewall_repair": ("reparo", ["REPARO"], 2, "Religar o Firewall",
                        "Firewall desligado não dá FPS e deixa o PC exposto. Religa."),
    "essential_services_repair": ("reparo", ["REPARO"], 2, "Religar serviços essenciais",
                                  "Som, rede, Windows Update e outros que outro otimizador desligou."),
    "write_cache_repair": ("reparo", ["REPARO", "DISCO"], 2, "Religar o cache de escrita do disco",
                           "Sem ele o PC inteiro fica lento. Religa se estiver desligado."),
    "trim_repair": ("reparo", ["REPARO", "SSD"], 2, "Religar o TRIM do SSD",
                    "O SSD perde velocidade com o tempo sem TRIM. Religa se estiver desligado."),
    "tcp_autotuning_repair": ("reparo", ["REPARO", "DOWNLOAD"], 2, "Consertar a velocidade de download",
                              "Um 'tweak de ping' famoso trava o download. Volta ao normal."),
    "bcd_timer_repair": ("reparo", ["REPARO", "-DELAY"], 2, "Tirar HPET forçado do boot",
                         "HPET forçado por outro otimizador AUMENTA o delay em CPU moderna. Remove."),
    "clear_pagefile_repair": ("reparo", ["REPARO"], 1, "Desligamento rápido de novo",
                              "Para o Windows de apagar a memória virtual inteira a cada desligamento."),
    "app_launch_cache_repair": ("reparo", ["REPARO"], 2, "Programas abrindo rápido de novo",
                                "Religa o SysMain e o Prefetcher, que outro otimizador desligou."),
}


def meta(task_id: str) -> Dict[str, Any]:
    goal, badges, impact, title, simple = _T.get(task_id, ("avancado", [], 1, "", ""))
    return {"goal": goal, "badges": list(badges), "impact": int(impact), "title": title, "simple": simple}


def known_ids() -> set:
    return set(_T)
